#!/usr/bin/env python3
"""
StreamLink Daemon Installer (7.1)
==================================
Registers (or removes) StreamLink as a system service so it starts on
login/boot and is supervised by the OS process manager.

  python3 run.py --install      # register the service
  python3 run.py --uninstall    # remove the service
  python3 run.py --status       # print current service status

Supported platforms
-------------------
macOS   → launchd   (~Library/LaunchAgents/com.streamlink.plist)
Linux   → systemd   (~/.config/systemd/user/streamlink.service)
Windows → Task Scheduler (user-level task via schtasks.exe)

The service runs:
    <venv>/bin/python watchdog.py    (the watchdog — keeps VLC/qBit/Jackett up)
    <venv>/bin/uvicorn main:app …   (the dashboard)

Both are launched by a tiny wrapper script (streamlink_service.py) so a
single process-group can be registered with the OS supervisor.
"""
from __future__ import annotations

import os
import platform
import subprocess
import sys
from pathlib import Path
from textwrap import dedent

HERE   = Path(__file__).parent
SYSTEM = platform.system()
VENV   = HERE / ".venv"

_VENV_PY = VENV / ("Scripts/python.exe" if SYSTEM == "Windows" else "bin/python")
_VENV_UV = VENV / ("Scripts/uvicorn.exe" if SYSTEM == "Windows" else "bin/uvicorn")

# ── Service wrapper script ─────────────────────────────────────────────────
# Written to the project root; the OS supervisor points at this.
_WRAPPER_NAME = "streamlink_service.py"
_WRAPPER_PATH = HERE / _WRAPPER_NAME

_WRAPPER_CONTENT = '''\
#!/usr/bin/env python3
"""
StreamLink service entry-point.
Mirrors the network-facing startup of `python run.py` (watchdog, mDNS,
Windows firewall rules, HTTPS admin process) and supervises the HTTP
uvicorn with automatic restarts. The watchdog handles VLC / qBit / Jackett,
so the service does not start those upfront.
Generated by daemon.py — do not edit by hand.
"""
from __future__ import annotations
import logging, subprocess, sys, time
from pathlib import Path

HERE = Path(__file__).parent
VENV = HERE / ".venv"

import platform, os
_SYSTEM = platform.system()
_UV = VENV / ("Scripts/uvicorn.exe" if _SYSTEM == "Windows" else "bin/uvicorn")

# File logging — Task Scheduler / launchd have no console
_log_dir = HERE / "logs"
_log_dir.mkdir(exist_ok=True)
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  [service]  %(levelname)-7s %(message)s",
    datefmt="%H:%M:%S",
    handlers=[logging.FileHandler(_log_dir / "streamlink_service.log", encoding="utf-8")],
)
log = logging.getLogger("streamlink.service")

# Add venv site-packages so watchdog.py and run.py helpers can import deps
# (psutil, zeroconf). Windows venv: Lib/site-packages. Unix: lib/pythonX.Y/site-packages.
import site
_sp_win = VENV / "Lib" / "site-packages"
if _sp_win.exists():
    site.addsitedir(str(_sp_win))
else:
    _sp = next((VENV / "lib").glob("python*/site-packages"), None)
    if _sp:
        site.addsitedir(str(_sp))

sys.path.insert(0, str(HERE))

# Start watchdog (monitors and launches VLC / qBit / Jackett)
try:
    from watchdog import start_watchdog
    start_watchdog()
    log.info("Watchdog started")
except Exception as exc:
    log.error("Watchdog failed to start: %s", exc)

# Reuse run.py helpers so the service uses the same LAN/mDNS/firewall logic
# as an interactive launch — keeps `python run.py` and the installed service
# behaviourally identical for these network bits.
_lan_ip = ""
try:
    from run import get_local_ip
    _lan_ip = get_local_ip()
    log.info("LAN IP detected: %s", _lan_ip or "(none)")
except Exception as exc:
    log.error("get_local_ip failed: %s", exc)

_CERT = HERE / "cert.pem"
_KEY  = HERE / "key.pem"
_has_cert = _CERT.exists() and _KEY.exists()

# Windows firewall — idempotent; Task Scheduler runs us elevated (/RL HIGHEST)
# so the netsh add-rule calls succeed.
if _SYSTEM == "Windows":
    try:
        from run import setup_windows_firewall
        setup_windows_firewall(80)
        if _has_cert:
            setup_windows_firewall(443)
        log.info("Windows firewall rules ensured")
    except Exception as exc:
        log.error("Firewall setup failed: %s", exc)

# mDNS — registers remote.local so phones can find the dashboard.
# Without this, the service binds port 80 fine but the LAN hostname doesn\'t resolve.
_zc = None
if _lan_ip:
    try:
        from run import start_mdns
        _zc = start_mdns(_lan_ip, 80, 443 if _has_cert else 0)
        if _zc:
            log.info("mDNS registered remote.local -> %s", _lan_ip)
        else:
            log.warning("mDNS registration returned None — remote.local will not resolve")
    except Exception as exc:
        log.error("mDNS registration failed: %s", exc)
else:
    log.warning("No LAN IP — skipping mDNS registration (remote.local will not resolve)")

# HTTPS admin uvicorn (port 443) — only if certs exist. Launched once; if it
# crashes the main HTTP service keeps running. Mirrors run.py interactive launch.
_https_proc = None
_https_log = None
if _has_cert:
    try:
        _https_log = open(_log_dir / "uvicorn_https.log", "ab")
        _https_proc = subprocess.Popen(
            [str(_UV), "main:app",
             "--host", "0.0.0.0",
             "--port", "443",
             "--ssl-certfile", str(_CERT),
             "--ssl-keyfile", str(_KEY),
             "--log-level", "warning"],
            cwd=str(HERE),
            stdout=_https_log,
            stderr=_https_log,
        )
        log.info("HTTPS uvicorn (port 443) launched, pid=%d", _https_proc.pid)
    except Exception as exc:
        log.error("HTTPS uvicorn launch failed: %s", exc)

# Supervise uvicorn (port 80) — restart on crash so a transient failure
# (e.g. port briefly busy at boot) doesn\'t kill the dashboard permanently.
_RESTART_DELAY    = 5.0
_FAST_DEATH_SECS  = 15.0   # death within this window counts as "fast"
_MAX_FAST_DEATHS  = 5      # give up after this many consecutive fast deaths

consecutive_fast = 0
try:
    while True:
        log.info("Starting uvicorn (%s)", _UV)
        t0 = time.monotonic()
        try:
            with open(_log_dir / "uvicorn.log", "ab") as uv_log:
                proc = subprocess.run(
                    [str(_UV), "main:app",
                     "--host", "0.0.0.0",
                     "--port", "80",
                     "--log-level", "warning"],
                    cwd=str(HERE),
                    stdout=uv_log,
                    stderr=uv_log,
                )
            rc = proc.returncode
        except FileNotFoundError:
            log.error("uvicorn not found at %s — re-run setup.py", _UV)
            break
        except Exception as exc:
            log.error("uvicorn launch error: %s", exc)
            rc = -1

        elapsed = time.monotonic() - t0
        log.info("uvicorn exited rc=%d after %.1fs", rc, elapsed)

        if rc == 0:
            log.info("Clean exit — service wrapper shutting down")
            break

        if elapsed < _FAST_DEATH_SECS:
            consecutive_fast += 1
        else:
            consecutive_fast = 0

        if consecutive_fast >= _MAX_FAST_DEATHS:
            log.error(
                "uvicorn crashed %d times in under %.0fs each — giving up. "
                "Check logs/uvicorn.log for the error.",
                consecutive_fast, _FAST_DEATH_SECS,
            )
            break

        log.info("Restarting uvicorn in %.0fs...", _RESTART_DELAY)
        time.sleep(_RESTART_DELAY)
finally:
    if _https_proc:
        try:
            _https_proc.terminate()
            _https_proc.wait(timeout=5)
        except Exception:
            pass
    if _https_log:
        try:
            _https_log.close()
        except Exception:
            pass
    if _zc:
        try:
            _zc.close()
        except Exception:
            pass

log.info("Service wrapper exiting")
'''

# ── Color output (reused from run.py style) ────────────────────────────────
_TTY = hasattr(sys.stdout, "isatty") and sys.stdout.isatty()
def _c(n): return f"\033[{n}m" if _TTY else ""
RESET = _c(0); BOLD = _c(1)
RED = _c(91); GRN = _c(92); YLW = _c(93); BLU = _c(94)

def ok(t):   print(f"  {GRN}✓{RESET}  {t}")
def warn(t): print(f"  {YLW}⚠{RESET}  {t}")
def fail(t): print(f"  {RED}✗{RESET}  {t}")
def info(t): print(f"  {BLU}→{RESET}  {t}")


# ── Sanity checks ─────────────────────────────────────────────────────────
def _check_venv() -> bool:
    if not _VENV_PY.exists():
        fail("Virtual environment not found. Run python3 setup.py first.")
        return False
    return True


def _write_wrapper() -> bool:
    try:
        _WRAPPER_PATH.write_text(_WRAPPER_CONTENT, encoding="utf-8")
        _WRAPPER_PATH.chmod(0o755)
        ok(f"Wrote service wrapper → {_WRAPPER_PATH.name}")
        return True
    except OSError as exc:
        fail(f"Could not write wrapper script: {exc}")
        return False


# ══════════════════════════════════════════════════════════════════════════
#  macOS — launchd
# ══════════════════════════════════════════════════════════════════════════
_LAUNCHD_LABEL = "com.streamlink.dashboard"
_LAUNCHD_PLIST = (
    Path.home() / "Library" / "LaunchAgents" / f"{_LAUNCHD_LABEL}.plist"
)

def _launchd_plist_content() -> str:
    log_dir = HERE / "logs"
    log_dir.mkdir(exist_ok=True)
    return dedent(f"""\
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
            "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
            <key>Label</key>
            <string>{_LAUNCHD_LABEL}</string>

            <key>ProgramArguments</key>
            <array>
                <string>{_VENV_PY}</string>
                <string>{_WRAPPER_PATH}</string>
            </array>

            <key>WorkingDirectory</key>
            <string>{HERE}</string>

            <key>RunAtLoad</key>
            <true/>

            <key>KeepAlive</key>
            <true/>

            <key>StandardOutPath</key>
            <string>{log_dir / "streamlink.log"}</string>

            <key>StandardErrorPath</key>
            <string>{log_dir / "streamlink.err"}</string>

            <key>EnvironmentVariables</key>
            <dict>
                <key>PATH</key>
                <string>/usr/local/bin:/opt/homebrew/bin:/usr/bin:/bin</string>
            </dict>
        </dict>
        </plist>
    """)


def _macos_install() -> bool:
    if not _check_venv():
        return False
    if not _write_wrapper():
        return False
    _LAUNCHD_PLIST.parent.mkdir(parents=True, exist_ok=True)
    _LAUNCHD_PLIST.write_text(_launchd_plist_content(), encoding="utf-8")
    ok(f"Wrote plist → {_LAUNCHD_PLIST}")

    # Unload first if already loaded (idempotent)
    subprocess.run(
        ["launchctl", "unload", str(_LAUNCHD_PLIST)],
        capture_output=True,
    )
    result = subprocess.run(
        ["launchctl", "load", "-w", str(_LAUNCHD_PLIST)],
        capture_output=True, text=True,
    )
    if result.returncode != 0:
        fail(f"launchctl load failed: {result.stderr.strip()}")
        return False
    ok("Service loaded via launchctl — StreamLink will start at login")
    info(f"Dashboard will be at http://remote.local  (or http://127.0.0.1)")
    info(f"Logs: {HERE / 'logs' / 'streamlink.log'}")
    return True


def _macos_uninstall() -> bool:
    if _LAUNCHD_PLIST.exists():
        subprocess.run(
            ["launchctl", "unload", "-w", str(_LAUNCHD_PLIST)],
            capture_output=True,
        )
        _LAUNCHD_PLIST.unlink()
        ok(f"Removed plist and unloaded service")
    else:
        warn("Launchd plist not found — nothing to remove")
    if _WRAPPER_PATH.exists():
        _WRAPPER_PATH.unlink()
        ok(f"Removed wrapper script")
    return True


def _macos_status() -> None:
    result = subprocess.run(
        ["launchctl", "list", _LAUNCHD_LABEL],
        capture_output=True, text=True,
    )
    if result.returncode == 0:
        ok(f"Service registered: {_LAUNCHD_LABEL}")
        print(result.stdout)
    else:
        warn("Service not registered with launchd")


# ══════════════════════════════════════════════════════════════════════════
#  Linux — systemd user unit
# ══════════════════════════════════════════════════════════════════════════
_SYSTEMD_UNIT_NAME = "streamlink.service"
_SYSTEMD_UNIT_DIR  = Path.home() / ".config" / "systemd" / "user"
_SYSTEMD_UNIT_PATH = _SYSTEMD_UNIT_DIR / _SYSTEMD_UNIT_NAME

def _systemd_unit_content() -> str:
    log_dir = HERE / "logs"
    log_dir.mkdir(exist_ok=True)
    return dedent(f"""\
        [Unit]
        Description=StreamLink — P2P media dashboard
        After=network.target

        [Service]
        Type=simple
        WorkingDirectory={HERE}
        ExecStart={_VENV_PY} {_WRAPPER_PATH}
        Restart=on-failure
        RestartSec=5
        StandardOutput=append:{log_dir / "streamlink.log"}
        StandardError=append:{log_dir / "streamlink.err"}
        Environment=PATH=/usr/local/bin:/usr/bin:/bin

        [Install]
        WantedBy=default.target
    """)


def _linux_install() -> bool:
    if not _check_venv():
        return False
    # Check systemd user session is available
    result = subprocess.run(
        ["systemctl", "--user", "is-system-running"],
        capture_output=True, text=True,
    )
    if result.returncode not in (0, 1):  # 1 = degraded but usable
        warn("systemd user session may not be available; proceeding anyway")

    if not _write_wrapper():
        return False
    _SYSTEMD_UNIT_DIR.mkdir(parents=True, exist_ok=True)
    _SYSTEMD_UNIT_PATH.write_text(_systemd_unit_content(), encoding="utf-8")
    ok(f"Wrote unit file → {_SYSTEMD_UNIT_PATH}")

    for cmd in [
        ["systemctl", "--user", "daemon-reload"],
        ["systemctl", "--user", "enable", _SYSTEMD_UNIT_NAME],
        ["systemctl", "--user", "start",  _SYSTEMD_UNIT_NAME],
    ]:
        r = subprocess.run(cmd, capture_output=True, text=True)
        if r.returncode != 0:
            fail(f"Command failed: {' '.join(cmd)}\n{r.stderr.strip()}")
            return False

    ok("Service enabled and started via systemd --user")
    info("StreamLink will start at login (requires lingering — see note below)")
    info("To start at boot without a login session:")
    info("  sudo loginctl enable-linger $USER")
    info(f"  journalctl --user -u {_SYSTEMD_UNIT_NAME} -f   (to follow logs)")
    return True


def _linux_uninstall() -> bool:
    if _SYSTEMD_UNIT_PATH.exists():
        for cmd in [
            ["systemctl", "--user", "stop",    _SYSTEMD_UNIT_NAME],
            ["systemctl", "--user", "disable",  _SYSTEMD_UNIT_NAME],
        ]:
            subprocess.run(cmd, capture_output=True)
        _SYSTEMD_UNIT_PATH.unlink()
        subprocess.run(["systemctl", "--user", "daemon-reload"], capture_output=True)
        ok("Service stopped, disabled, and unit file removed")
    else:
        warn("Unit file not found — nothing to remove")
    if _WRAPPER_PATH.exists():
        _WRAPPER_PATH.unlink()
        ok("Removed wrapper script")
    return True


def _linux_status() -> None:
    result = subprocess.run(
        ["systemctl", "--user", "status", _SYSTEMD_UNIT_NAME],
        capture_output=True, text=True,
    )
    print(result.stdout or result.stderr)


# ══════════════════════════════════════════════════════════════════════════
#  Windows — Task Scheduler
# ══════════════════════════════════════════════════════════════════════════
_WIN_TASK_NAME = "StreamLink"


def _is_windows_admin() -> bool:
    try:
        import ctypes
        return bool(ctypes.windll.shell32.IsUserAnAdmin())
    except Exception:
        return False


def _windows_console_user() -> str:
    """Return the user interactively logged in to the console session, e.g.
    'PC\\nathan' — empty string if we can't determine it.

    Why this exists: when the user runs from an elevated Admin shell (UAC),
    `os.environ['USERNAME']` is the *Admin* account, not the regular user
    who's actually logged in. Registering a Task Scheduler entry with
    `/RU Admin /SC ONLOGON` ties it to Admin's logon, so the task never fires
    at the regular user's logon and the service silently fails to start.
    We query the console session to find the real interactive user instead.
    """
    # First try: ctypes via WTSGetActiveConsoleSessionId + Win32 lookup.
    # Works on every Windows edition incl. Home.
    try:
        import ctypes
        from ctypes import wintypes

        session_id = ctypes.windll.kernel32.WTSGetActiveConsoleSessionId()
        if session_id != 0xFFFFFFFF:
            WTS_CURRENT_SERVER_HANDLE = 0
            WTSUserName = 5    # WTS_INFO_CLASS.WTSUserName
            WTSDomainName = 7  # WTS_INFO_CLASS.WTSDomainName

            def _query(info_class: int) -> str:
                buf = ctypes.c_void_p()
                length = wintypes.DWORD()
                ok_ = ctypes.windll.wtsapi32.WTSQuerySessionInformationW(
                    WTS_CURRENT_SERVER_HANDLE, session_id, info_class,
                    ctypes.byref(buf), ctypes.byref(length),
                )
                if not ok_ or not buf.value:
                    return ""
                try:
                    return ctypes.wstring_at(buf.value)
                finally:
                    ctypes.windll.wtsapi32.WTSFreeMemory(buf)

            user = _query(WTSUserName)
            if user:
                domain = _query(WTSDomainName)
                return f"{domain}\\{user}" if domain else user
    except Exception:
        pass

    # Fallback: PowerShell CIM query. Returns DOMAIN\username.
    try:
        r = subprocess.run(
            ["powershell", "-NoProfile", "-Command",
             "(Get-CimInstance -ClassName Win32_ComputerSystem).UserName"],
            capture_output=True, text=True, timeout=10,
        )
        if r.returncode == 0:
            user = r.stdout.strip()
            if user:
                return user
    except Exception:
        pass

    return ""


def _windows_install() -> bool:
    if not _check_venv():
        return False

    # schtasks /Create with /RL HIGHEST needs an elevated token. If we're not
    # elevated, relaunch `run.py --install` through the UAC prompt — it
    # re-enters this function as admin and finishes the job.
    if not _is_windows_admin():
        warn("Administrator rights are required to register the scheduled task.")
        info("Requesting elevation — accept the UAC prompt …")
        try:
            import ctypes
            script = str(HERE / "run.py")
            rc = ctypes.windll.shell32.ShellExecuteW(
                None, "runas", sys.executable, f'"{script}" --install', str(HERE), 1
            )
            if rc <= 32:
                fail(f"Elevation was declined or failed (ShellExecute code {rc}).")
                info("Re-run from an Administrator PowerShell:  python run.py --install")
                return False
            ok("Elevated installer launched in a new window — watch it for the result.")
            return True
        except Exception as exc:
            fail(f"Could not request elevation: {exc}")
            info("Re-run from an Administrator PowerShell:  python run.py --install")
            return False

    # ── Running as admin (elevated child process) ─────────────────────────
    # The elevated console window closes the instant we exit, so wrap everything
    # in try/finally and pause at the end so the user can read the output.
    # Also reconfigure stdout/stderr for UTF-8 in case the new console opened
    # with a legacy code page (cp437, cp1252) that can't render ✓ / ⚠ / →.
    try:
        import sys as _sys
        if hasattr(_sys.stdout, "reconfigure"):
            _sys.stdout.reconfigure(encoding="utf-8", errors="replace")
        if hasattr(_sys.stderr, "reconfigure"):
            _sys.stderr.reconfigure(encoding="utf-8", errors="replace")
    except Exception:
        pass

    try:
        if not _write_wrapper():
            return False

        py  = str(_VENV_PY)
        scr = str(_WRAPPER_PATH)

        # Pick the user account the task will run as. When we elevated via UAC
        # (or the user opened an Admin shell as a different account), USERNAME
        # is the *admin* account, not the user actually sitting at the box.
        # Registering /SC ONLOGON for the admin means the task only fires when
        # the admin logs in — so the regular user sees no service. Query the
        # console session to find the interactive user instead.
        env_user = os.environ.get("USERNAME", "")
        console_user = _windows_console_user()
        if console_user:
            run_user = console_user
            # Drop the DOMAIN\\ prefix only when it matches COMPUTERNAME, so
            # local accounts stay portable across renames. Keep domain prefix
            # for actual domain accounts.
            comp = os.environ.get("COMPUTERNAME", "")
            if "\\" in console_user:
                dom, _, name = console_user.partition("\\")
                if comp and dom.upper() == comp.upper():
                    run_user = name
            if console_user.split("\\")[-1].lower() != env_user.lower():
                info(f"Detected console user '{console_user}' differs from "
                     f"current USERNAME '{env_user}' (likely UAC elevation).")
            info(f"Service will run as: {run_user}")
        else:
            run_user = env_user
            warn(f"Could not detect the console user — falling back to "
                 f"USERNAME='{env_user}'. If you installed from an Admin "
                 f"shell, the task may not fire at your regular user's logon. "
                 f"Re-run --install while logged in as the account that "
                 f"should run the service.")

        # Add firewall rules now while we have an admin token (UAC just gave
        # us one). The running task may be a Standard User — they can't add
        # netsh rules, so we set them up here and they persist.
        try:
            sys.path.insert(0, str(HERE))
            from run import setup_windows_firewall as _fw
            _fw(80)
            if (HERE / "cert.pem").exists() and (HERE / "key.pem").exists():
                _fw(443)
        except Exception as exc:
            warn(f"Could not add firewall rules: {exc}")

        # schtasks /Create — fires at the chosen user's logon.
        #
        # Note: we deliberately do NOT pass /RL HIGHEST. On Windows, the
        # restriction on ports < 1024 is a Unix-ism — any user can bind port
        # 80/443 as long as the port is free and not reserved by http.sys.
        # Passing HIGHEST would make Task Scheduler try to elevate the user's
        # token at trigger time, which fails silently for Standard Users
        # (no admin rights to elevate to) — the task appears registered but
        # never actually runs. Without HIGHEST, the task launches under the
        # user's normal token and works for everyone.
        #
        # stdin=DEVNULL prevents schtasks from hanging if it ever prompts for
        # a password (e.g. on certain domain configurations — ONLOGON tasks
        # don't actually need one).
        cmd = [
            "schtasks", "/Create", "/F",
            "/TN", _WIN_TASK_NAME,
            "/TR", f'"{py}" "{scr}"',
            "/SC", "ONLOGON",
            "/RU", run_user,
        ]
        result = subprocess.run(
            cmd, capture_output=True, text=True, shell=False,
            stdin=subprocess.DEVNULL,
        )
        if result.returncode != 0:
            fail(f"schtasks /Create failed:\n{result.stderr.strip()}")
            return False
        ok(f"Task '{_WIN_TASK_NAME}' created in Task Scheduler (RunAs: {run_user})")

        # Start it now. schtasks /Run respects /RU — if that user is logged
        # in, the wrapper launches in their session. If not, it may report
        # success but never actually start, so we don't over-trust the rc here.
        start = subprocess.run(
            ["schtasks", "/Run", "/TN", _WIN_TASK_NAME],
            capture_output=True, text=True,
            stdin=subprocess.DEVNULL,
        )
        if start.returncode == 0:
            ok("Task started immediately")
        else:
            warn(f"Task registered but could not start immediately:\n"
                 f"  stdout: {(start.stdout or '').strip()}\n"
                 f"  stderr: {(start.stderr or '').strip()}\n"
                 f"  It will run at next logon for {run_user}.")
        info("Dashboard -> http://remote.local  (or http://127.0.0.1)")
        info("Service log -> logs\\streamlink_service.log")
        info("If something seems wrong, run:  python run.py --diagnose")
        return True

    finally:
        # Keep the elevated window open so the user can read the result.
        try:
            input("\n  Press Enter to close this window …\n")
        except EOFError:
            pass


def _windows_uninstall() -> bool:
    result = subprocess.run(
        ["schtasks", "/Delete", "/F", "/TN", _WIN_TASK_NAME],
        capture_output=True, text=True,
    )
    if result.returncode == 0:
        ok(f"Task '{_WIN_TASK_NAME}' removed from Task Scheduler")
    else:
        warn(f"Could not remove task (may not exist): {result.stderr.strip()}")
    if _WRAPPER_PATH.exists():
        _WRAPPER_PATH.unlink()
        ok("Removed wrapper script")
    return True


def _windows_status() -> None:
    result = subprocess.run(
        ["schtasks", "/Query", "/TN", _WIN_TASK_NAME, "/FO", "LIST"],
        capture_output=True, text=True,
    )
    if result.returncode == 0:
        print(result.stdout)
    else:
        warn(f"Task '{_WIN_TASK_NAME}' not found in Task Scheduler")


# ── Public API ─────────────────────────────────────────────────────────────
def install() -> bool:
    print(f"\n{BOLD}  StreamLink — Install as system service{RESET}\n")
    if SYSTEM == "Darwin":
        return _macos_install()
    elif SYSTEM == "Linux":
        return _linux_install()
    elif SYSTEM == "Windows":
        return _windows_install()
    else:
        fail(f"Unsupported platform: {SYSTEM}")
        return False


def uninstall() -> bool:
    print(f"\n{BOLD}  StreamLink — Remove system service{RESET}\n")
    if SYSTEM == "Darwin":
        return _macos_uninstall()
    elif SYSTEM == "Linux":
        return _linux_uninstall()
    elif SYSTEM == "Windows":
        return _windows_uninstall()
    else:
        fail(f"Unsupported platform: {SYSTEM}")
        return False


def status() -> None:
    print(f"\n{BOLD}  StreamLink — Service status{RESET}\n")
    if SYSTEM == "Darwin":
        _macos_status()
    elif SYSTEM == "Linux":
        _linux_status()
    elif SYSTEM == "Windows":
        _windows_status()
    else:
        warn(f"Unsupported platform: {SYSTEM}")
