#!/usr/bin/env python3
"""
StreamLink service entry-point.
Mirrors the network-facing startup of `python run.py` (watchdog, mDNS,
Windows firewall rules) and supervises the uvicorn servers with automatic
restarts. The watchdog handles VLC / qBit / Jackett, so the service does
not start those upfront.
Generated by daemon.py — do not edit by hand.
"""
from __future__ import annotations
import asyncio, logging, sys, time
from pathlib import Path

HERE = Path(__file__).parent
VENV = HERE / ".venv"

import platform, os
_SYSTEM = platform.system()

# File logging — Task Scheduler / launchd have no console
_log_dir = HERE / "logs"
_log_dir.mkdir(exist_ok=True)
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  [service]  %(levelname)-7s %(message)s",
    datefmt="%H:%M:%S",
    handlers=[logging.FileHandler(_log_dir / "streamlink_service.log", encoding="utf-8")],
)
log = logging.getLogger("streamlink.service")

# Add venv site-packages so watchdog.py and run.py helpers can import deps
# (psutil, zeroconf). Windows venv: Lib/site-packages. Unix: lib/pythonX.Y/site-packages.
import site
_sp_win = VENV / "Lib" / "site-packages"
if _sp_win.exists():
    site.addsitedir(str(_sp_win))
else:
    _sp = next((VENV / "lib").glob("python*/site-packages"), None)
    if _sp:
        site.addsitedir(str(_sp))

sys.path.insert(0, str(HERE))

# Start watchdog (monitors and launches VLC / qBit / Jackett)
try:
    from watchdog import start_watchdog
    start_watchdog()
    log.info("Watchdog started")
except Exception as exc:
    log.error("Watchdog failed to start: %s", exc)

# Reuse run.py helpers so the service uses the same LAN/mDNS/firewall logic
# as an interactive launch — keeps `python run.py` and the installed service
# behaviourally identical for these network bits.
_lan_ip = ""
try:
    from run import get_local_ip
    _lan_ip = get_local_ip()
    log.info("LAN IP detected: %s", _lan_ip or "(none)")
except Exception as exc:
    log.error("get_local_ip failed: %s", exc)

_CERT = HERE / "cert.pem"
_KEY  = HERE / "key.pem"
_has_cert = _CERT.exists() and _KEY.exists()

# Windows firewall — idempotent; Task Scheduler runs us elevated (/RL HIGHEST)
# so the netsh add-rule calls succeed.
if _SYSTEM == "Windows":
    try:
        from run import setup_windows_firewall
        setup_windows_firewall(80)
        if _has_cert:
            setup_windows_firewall(443)
        log.info("Windows firewall rules ensured")
    except Exception as exc:
        log.error("Firewall setup failed: %s", exc)

# mDNS — registers remote.local so phones can find the dashboard. RESILIENT:
# at boot the service starts before Wi-Fi has associated, so a one-shot
# registration would see no LAN IP and silently skip it — remote.local would
# then never resolve until a manual relaunch even though uvicorn (0.0.0.0) is
# reachable by IP the moment the network comes up. start_mdns_resilient waits
# for the LAN IP in a background thread and re-registers if it changes.
# See docs/GOTCHAS.md.
_zc = None
try:
    from run import start_mdns_resilient
    _zc = start_mdns_resilient(80, 443 if _has_cert else 0)
    log.info("mDNS keepalive started (registers remote.local once a LAN IP is up)")
except Exception as exc:
    log.error("mDNS keepalive failed to start: %s", exc)

# Run HTTP (port 80) and HTTPS (port 443) in the SAME asyncio event loop so
# both servers share the AppState module global in main.py. Two separate
# processes (the previous approach) had separate memory and showed stale state
# to clients on the other port.
#
# log_config suppresses uvicorn's default dictConfig which adds StreamHandlers
# pointing at sys.stderr/stdout — those are None in a Task Scheduler service
# (no console), causing uvicorn to fail silently on startup.
_UV_LOG_CFG = {"version": 1, "disable_existing_loggers": False}

async def _launch_servers():
    import uvicorn as _uvicorn
    log.info("Configuring uvicorn servers (HTTP port 80%s)", ", HTTPS port 443" if _has_cert else "")
    http_cfg = _uvicorn.Config(
        "main:app", host="0.0.0.0", port=80,
        log_level="warning", log_config=_UV_LOG_CFG,
    )
    http_srv = _uvicorn.Server(http_cfg)
    http_srv.install_signal_handlers = lambda: None
    coros = [http_srv.serve()]
    if _has_cert:
        https_cfg = _uvicorn.Config(
            "main:app", host="0.0.0.0", port=443,
            ssl_certfile=str(_CERT), ssl_keyfile=str(_KEY),
            log_level="warning", log_config=_UV_LOG_CFG,
            lifespan="off",
        )
        https_srv = _uvicorn.Server(https_cfg)
        https_srv.install_signal_handlers = lambda: None
        coros.append(https_srv.serve())
    results = await asyncio.gather(*coros, return_exceptions=True)
    for i, r in enumerate(results):
        if isinstance(r, BaseException):
            log.error("Server %d exited with exception: %s: %s", i, type(r).__name__, r)
    if hasattr(http_srv, "started") and not http_srv.started:
        raise RuntimeError("HTTP server (port 80) failed to start — port may be in use or permission denied")

# Supervise — restart whenever the servers stop so a transient failure
# (e.g. port briefly busy at boot) doesn't kill the dashboard permanently.
# The service is only stopped via explicit OS signal (KeyboardInterrupt /
# SystemExit) or after _MAX_FAST_DEATHS consecutive quick crashes.
_RESTART_DELAY    = 5.0
_FAST_DEATH_SECS  = 15.0   # death within this window counts as "fast"
_MAX_FAST_DEATHS  = 5      # give up after this many consecutive fast deaths

consecutive_fast = 0
try:
    while True:
        log.info("Starting uvicorn servers")
        t0 = time.monotonic()
        try:
            asyncio.run(_launch_servers())
        except (KeyboardInterrupt, SystemExit):
            log.info("Interrupted — stopping service")
            break
        except Exception as exc:
            log.error("Server error: %s: %s", type(exc).__name__, exc)

        elapsed = time.monotonic() - t0
        log.info("Servers exited after %.1fs — restarting", elapsed)

        if elapsed < _FAST_DEATH_SECS:
            consecutive_fast += 1
        else:
            consecutive_fast = 0

        if consecutive_fast >= _MAX_FAST_DEATHS:
            log.error(
                "Servers crashed %d times in under %.0fs each — giving up. "
                "Check logs/streamlink_service.log for the error.",
                consecutive_fast, _FAST_DEATH_SECS,
            )
            break

        log.info("Restarting servers in %.0fs...", _RESTART_DELAY)
        time.sleep(_RESTART_DELAY)
finally:
    if _zc:
        try:
            _zc.close()
        except Exception:
            pass

log.info("Service wrapper exiting")
