#!/usr/bin/env python3
"""
StreamLink service entry-point.
Mirrors the network-facing startup of `python run.py` (watchdog, mDNS,
Windows firewall rules, HTTPS admin process) and supervises the HTTP
uvicorn with automatic restarts. The watchdog handles VLC / qBit / Jackett,
so the service does not start those upfront.
Generated by daemon.py — do not edit by hand.
"""
from __future__ import annotations
import logging, subprocess, sys, time
from pathlib import Path

HERE = Path(__file__).parent
VENV = HERE / ".venv"

import platform, os
_SYSTEM = platform.system()
_UV = VENV / ("Scripts/uvicorn.exe" if _SYSTEM == "Windows" else "bin/uvicorn")

# File logging — Task Scheduler / launchd have no console
_log_dir = HERE / "logs"
_log_dir.mkdir(exist_ok=True)
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  [service]  %(levelname)-7s %(message)s",
    datefmt="%H:%M:%S",
    handlers=[logging.FileHandler(_log_dir / "streamlink_service.log", encoding="utf-8")],
)
log = logging.getLogger("streamlink.service")

# Add venv site-packages so watchdog.py and run.py helpers can import deps
# (psutil, zeroconf). Windows venv: Lib/site-packages. Unix: lib/pythonX.Y/site-packages.
import site
_sp_win = VENV / "Lib" / "site-packages"
if _sp_win.exists():
    site.addsitedir(str(_sp_win))
else:
    _sp = next((VENV / "lib").glob("python*/site-packages"), None)
    if _sp:
        site.addsitedir(str(_sp))

sys.path.insert(0, str(HERE))

# Start watchdog (monitors and launches VLC / qBit / Jackett)
try:
    from watchdog import start_watchdog
    start_watchdog()
    log.info("Watchdog started")
except Exception as exc:
    log.error("Watchdog failed to start: %s", exc)

# Reuse run.py helpers so the service uses the same LAN/mDNS/firewall logic
# as an interactive launch — keeps `python run.py` and the installed service
# behaviourally identical for these network bits.
_lan_ip = ""
try:
    from run import get_local_ip
    _lan_ip = get_local_ip()
    log.info("LAN IP detected: %s", _lan_ip or "(none)")
except Exception as exc:
    log.error("get_local_ip failed: %s", exc)

_CERT = HERE / "cert.pem"
_KEY  = HERE / "key.pem"
_has_cert = _CERT.exists() and _KEY.exists()

# Windows firewall — idempotent; Task Scheduler runs us elevated (/RL HIGHEST)
# so the netsh add-rule calls succeed.
if _SYSTEM == "Windows":
    try:
        from run import setup_windows_firewall
        setup_windows_firewall(80)
        if _has_cert:
            setup_windows_firewall(443)
        log.info("Windows firewall rules ensured")
    except Exception as exc:
        log.error("Firewall setup failed: %s", exc)

# mDNS — registers remote.local so phones can find the dashboard. RESILIENT:
# at boot the service starts before Wi-Fi has associated, so a one-shot
# registration would see no LAN IP and silently skip it — remote.local would
# then never resolve until a manual relaunch even though uvicorn (0.0.0.0) is
# reachable by IP the moment the network comes up. start_mdns_resilient waits
# for the LAN IP in a background thread and re-registers if it changes.
# See docs/GOTCHAS.md.
_zc = None
try:
    from run import start_mdns_resilient
    _zc = start_mdns_resilient(80, 443 if _has_cert else 0)
    log.info("mDNS keepalive started (registers remote.local once a LAN IP is up)")
except Exception as exc:
    log.error("mDNS keepalive failed to start: %s", exc)

# HTTPS admin uvicorn (port 443) — only if certs exist. Launched once; if it
# crashes the main HTTP service keeps running. Mirrors run.py interactive launch.
_https_proc = None
_https_log = None
if _has_cert:
    try:
        _https_log = open(_log_dir / "uvicorn_https.log", "ab")
        _https_proc = subprocess.Popen(
            [str(_UV), "main:app",
             "--host", "0.0.0.0",
             "--port", "443",
             "--ssl-certfile", str(_CERT),
             "--ssl-keyfile", str(_KEY),
             "--log-level", "warning"],
            cwd=str(HERE),
            stdout=_https_log,
            stderr=_https_log,
        )
        log.info("HTTPS uvicorn (port 443) launched, pid=%d", _https_proc.pid)
    except Exception as exc:
        log.error("HTTPS uvicorn launch failed: %s", exc)

# Supervise uvicorn (port 80) — restart on crash so a transient failure
# (e.g. port briefly busy at boot) doesn't kill the dashboard permanently.
_RESTART_DELAY    = 5.0
_FAST_DEATH_SECS  = 15.0   # death within this window counts as "fast"
_MAX_FAST_DEATHS  = 5      # give up after this many consecutive fast deaths

consecutive_fast = 0
try:
    while True:
        log.info("Starting uvicorn (%s)", _UV)
        t0 = time.monotonic()
        try:
            with open(_log_dir / "uvicorn.log", "ab") as uv_log:
                proc = subprocess.run(
                    [str(_UV), "main:app",
                     "--host", "0.0.0.0",
                     "--port", "80",
                     "--log-level", "warning"],
                    cwd=str(HERE),
                    stdout=uv_log,
                    stderr=uv_log,
                )
            rc = proc.returncode
        except FileNotFoundError:
            log.error("uvicorn not found at %s — re-run setup.py", _UV)
            break
        except Exception as exc:
            log.error("uvicorn launch error: %s", exc)
            rc = -1

        elapsed = time.monotonic() - t0
        log.info("uvicorn exited rc=%d after %.1fs", rc, elapsed)

        if rc == 0:
            log.info("Clean exit — service wrapper shutting down")
            break

        if elapsed < _FAST_DEATH_SECS:
            consecutive_fast += 1
        else:
            consecutive_fast = 0

        if consecutive_fast >= _MAX_FAST_DEATHS:
            log.error(
                "uvicorn crashed %d times in under %.0fs each — giving up. "
                "Check logs/uvicorn.log for the error.",
                consecutive_fast, _FAST_DEATH_SECS,
            )
            break

        log.info("Restarting uvicorn in %.0fs...", _RESTART_DELAY)
        time.sleep(_RESTART_DELAY)
finally:
    if _https_proc:
        try:
            _https_proc.terminate()
            _https_proc.wait(timeout=5)
        except Exception:
            pass
    if _https_log:
        try:
            _https_log.close()
        except Exception:
            pass
    if _zc:
        try:
            _zc.close()
        except Exception:
            pass

log.info("Service wrapper exiting")
